allowBuilds:
  lzma-native: false
autoInstallPeers: true
engineStrict: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@toonamfjs/bytearray-node@1.0.1'
packages:
  - 'bytearray-node'
  - 'client'
  - 'server'
